### ISSUE TITLE
Всякая мелочь в презентациях

### ISSUE THREAD

**Issue by andrey-komarov** [jagajaga/FP-Course-2015#1]
#### Lists

`listExample !! 0` --- `O(n)` time

Скорее, не `O(n)` (`n`, скорее всего, будет принято за длину списка), а `O(i)`, где `list !! i`
#### Sum of Types

Казалось бы, [Sum types](https://en.wikipedia.org/wiki/Tagged_union).
Ещё, если что, в C++ тоже есть enum-ы (а в c++11 они даже настоящие, а не просто целые числа).
#### Production of types

Казалось бы, [Product types](https://en.wikipedia.org/wiki/Product_type). 
(а в c++11 они даже настоящие, а не просто целые числа).

Тут ещё можно лирическое отступление с интуицией о том, почему они называются сумма и произведение, соответственно ~~и фокус со взятием производной типа~~
#### Haskell comparable SumList

Грешно сравнивать суммы даблов на == :(
#### Record syntax

Раз есть `rules User { login = "root" } = Root`, можно ещё добавить симметричное Record Update `makeRoot user = user { login = "root" }`
#### More type bounds examples

Раз уж есть undefined, можно ещё про дырки рассказать. Когда в GHC 7.10 добавили дырки, на хаскеле наконец-то стало можно писать.

**Comment by chshersh** [comment]
### Третья лекция

Да, можно сказать точней, чтобы не вводить в заблуждение, ок.

### Четвёртая лекция

#### Sum types

Ок, заголовок пофиксил. А про enum в С++ можно сказать, просто не хотел на презентацию вставлять, если там то же самое или хуже.

#### Product types

Про заголовок &mdash; ок. А про производную не стоит говорить, это будет в лекции про зипперы. Можно только отправить читать эту часть: [zippers](http://neerc.ifmo.ru/wiki/index.php?title=%D0%9F%D1%80%D0%BE%D1%82%D0%B8%D0%B2%D0%BE%D1%8F%D0%BD#zippers_and_functions_differentiation)

#### Haskell comparable SumList

Ты имеешь в виду, что нужны эпсилоны?) Думаю, можно заменить везде заменить на список интов, никто не пострадает, чтобы лишних тонких вопросов не поднимать.

#### Record syntax

Не хотел специально говорить про record update на лекции. Им его придётся в домашнем задании сделать, так что пусть почитают ссылку и узнают, как это сделать.

#### More type bounds examples

Уж если что и имеет смысл добавить, так это скорей error :) Что я и сделал.
Думаю, про typed holes будет немного сложновато в начале восприниматься. Пока что поместил их в uncovered topics. Может быть найдётся время для лекции, чтобы закрыть все долги по клёвым темам и рассказать их.

**Comment by jagajaga** [comment]
**More type bounds examples**

Нет. Про `_` из ghc 7.10 надо рассказать.

**Comment by chshersh** [comment]
Да я не против про них рассказать вообще, как и про всё из uncovered topics. Надо просто подумать, куда про typed holes вставить. Но я думаю, что в начальные лекции их точно не стоит впихивать. Студенты пусть разберутся с основами. Да и работать они будут пока с простыми типами, смогут и без typed holes обойтись, к тому же, будет полезно без них поразбираться в происходящем. А когда пойдёт что-то сложное типа Lens, тогда можно заодно и про typed holes поведать.

И вообще, это уже вопрос по курсу, а не по презентациям. Давайте их в отдельный issue выделим. Кто хочет обсуждать курс и вносить конструктивные адекватные предложения, пишите в issue про курс и создайте его вначале, если он отсутствует.
