### ISSUE TITLE
Apply convention to lecture formatting

### ISSUE THREAD

**Issue by chshersh** [jagajaga/FP-Course-2015#2]
I propose to invent and follow some convention for this course and format whole course according to this convention. I propose the following:

* Use double star ** for bold.
* Use underscore _ for italics.

1. Keywords should be **bold** plain text. 
    Example: **data**
2. Packages should be in `backticks` with link to Hackage. 
    Example: [`lens`](https://hackage.haskell.org/package/lens)
3. Functions and operators from libraries should be in italics and in backtics with link to Hackage. 
    Example: [_`whenJust`_](https://hackage.haskell.org/package/universum-1.0.4.1/docs/Universum-Monad-Maybe.html#v:whenJust)
4. Language extensions should be in _italics_ with link to haskell user guide started with `-X`. 
    Example: [_-XRecordWildCards_](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#record-wildcards)
5. Compiler options should be bold with monospace.
    Example: **`-ddump-deriv`**

**Comment by zclimber** [comment]
Корчагин

**Comment by chshersh** [comment]
@zclimber :ok_hand: You can start doing this

**Comment by chshersh** [comment]
Resolved in #3
